# Generated by Django 4.2.21 on 2026-03-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_name', models.CharField(default='MAHS', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.URLField(blank=True)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('about_title', models.CharField(default='About Our School', max_length=255)),
                ('about_text', models.TextField(blank=True)),
                ('principal_name', models.CharField(blank=True, max_length=255)),
                ('principal_message', models.TextField(blank=True)),
                ('principal_photo', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
