# Generated by Django 4.2.21 on 2026-03-26 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('notice', 'Notice'), ('news', 'News'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('admission', 'Admission')], default='notice', max_length=20)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
